name: .NET

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (no package)
        run: dotnet build -c Release --no-restore /p:GeneratePackageOnBuild=false

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Bump & push tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
            github_token: ${{ github.token }}
            default_bump: minor
            tag_prefix: ""

      - name: Fetch tags
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: git fetch --tags --force

      - name: Build (package with new tag)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: dotnet build -c Release --no-restore /p:GeneratePackageOnBuild=true

      - name: Publish NuGet
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
            dotnet nuget push "**/*.nupkg" --api-key "$NUGET" --source "https://api.nuget.org/v3/index.json" --skip-duplicate --no-symbols
        env:
            NUGET: ${{ secrets.NUGET }}

      - name: Create Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          
